//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoseanGE {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ThemeColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static ThemeColor defaultInstance = ((ThemeColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ThemeColor())));
        
        public static ThemeColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 83, 13")]
        public global::System.Drawing.Color Top {
            get {
                return ((global::System.Drawing.Color)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 83, 13")]
        public global::System.Drawing.Color Drawer {
            get {
                return ((global::System.Drawing.Color)(this["Drawer"]));
            }
            set {
                this["Drawer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 83, 13")]
        public global::System.Drawing.Color Panel {
            get {
                return ((global::System.Drawing.Color)(this["Panel"]));
            }
            set {
                this["Panel"] = value;
            }
        }
    }
}
